### ISSUE TITLE
In a CRM databases login not work

### ISSUE THREAD

**Issue by pranaysonisoft** [EasyERP/EasyERP_open_source#1]
In a CRM  databases 
User : superAdmin   and     Password  : 111111

Not Working. i restore all dump.

when i select saas login work but in CRM   db
(Wrong Password or such user doesn't registered  )  Message show 

i check db  in Robomongo   **Users** Collection not exist in **CRM** db

**Comment by PikinerLiliya** [comment]
Try to drop CRM database and restore it again, I'm afraid that was some error durin mongorestore
