### ISSUE TITLE
Update mongoose 

### ISSUE THREAD

**Issue by khubo** [EasyERP/EasyERP_open_source#14]
the current version of mongoose that is being used is having issues with the latest mongodb. Can you please update it to the latest? 

p.s : I can make a PR 😸

**Comment by jacksolutions** [comment]
do you have a working version of Easy erp? it is not at all working, lots of errors and bugs, if you have working version, can you please share?

**Comment by khubo** [comment]
@jacksolutions this is a working [branch](https://github.com/khubo/EasyERP_open_source/tree/update-mongoose)

**Comment by jacksolutions** [comment]
Thank you very much, let me check and get back to you.

Thanks

**Comment by jacksolutions** [comment]
whats the future of easyerp, it seems like the author is so busy on his own business that they are not focusing on this wonderful erp, there are no commits since last 5 months, i tried to connect them many times and after some weeks i got an email saying they are very busy with customization work that they are getting so they are hardly focusing on it, how we can take this ERP further by developing more modules on top of it? any roadmap?

**Comment by khubo** [comment]
@jacksolutions i am in no way connected to this project. I was just helping out someone, and thought someone will fix this issue. I have made a PR anyway.

**Comment by jacksolutions** [comment]
i cloned from your repo and set it up perfectly but it is stuck at login screen with this error

GET
https://apis.google.com/_/scs/apps-static/_/js/k=oz.gapi.en.IFwVvBRasIE.O/m=auth/rt=j/sv=1/d=1/ed=1/am=AQE/rs=AGLTcCPhIWMC-XBs_FOjL7nFPINRnwlHXA/cb=gapi.loaded_0
[HTTP/2.0 200 OK 0ms]
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://a52cae72-0b90-4548-97d9-3a5532918830/js/resources/lib/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map
[Learn More]
CSI/tbsd_
cb=gapi.loaded_0:459:127
CSI/_tbnd
cb=gapi.loaded_0:459:127
GET
https://accounts.google.com/o/oauth2/postmessageRelay
[HTTP/2.0 200 OK 109ms]
GETXHR
http://localhost:8089/modules/
[HTTP/1.1 500 Internal Server Error 27ms]
Error: No collection received from fetch

**Comment by jacksolutions** [comment]
are you getting the same error? please help

**Comment by khubo** [comment]
@jacksolutions try google chrome . there are some browser issues.

**Comment by jacksolutions** [comment]
GET /account/authenticated?_=1516882361054 200 3.363 ms - 2
2018-01-25T12:12:42.292Z - error: The 'cursor' option is required, except for aggregate with the explain argument
MongoError: The 'cursor' option is required, except for aggregate with the explain argument
    at Function.MongoError.create (/Users/jacksolutions/Documents/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/error.js:31:11)
    at /Users/jacksolutions/Documents/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:793:66
    at Callbacks.emit (/Users/jacksolutions/Documents/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:94:3)
    at Connection.messageHandler (/Users/jacksolutions/Documents/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/topologies/server.js:235:23)
    at Socket.<anonymous> (/Users/jacksolutions/Documents/EasyERP_open_source/node_modules/mongoose/node_modules/mongodb-core/lib/connection/connection.js:259:22)
    at Socket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at Socket.Readable.push (_stream_readable.js:209:10)
    at TCP.onread (net.js:608:20)
GET /modules/ 500 10.509 ms - 91

**Comment by khubo** [comment]
@jacksolutions did u mongorestore ? helping you debug like this is hard lol. also this is a ditched project.

**Comment by jacksolutions** [comment]
hahaha yes true, this is ditched project, yes i did mongorestore and it went well, i can see dbs too in my database

**Comment by khubo** [comment]
@jacksolutions also, if u are using my branch, make sure u reinstall alll teh node_modules. 
` rm -rf node_modules
   npm i
`

**Comment by jacksolutions** [comment]
when i cloned it, there is no node-modules folder and i had to do npm i and bower i

i did it both also redis server is installed and running and connecting fine.

let me re do the mongorestore again

**Comment by jacksolutions** [comment]
okay so it asked me for jquery version during installation, i choose 1 is it correct?

there were like around 1 to 7 options

**Comment by khubo** [comment]
@jacksolutions yeah, go for it.

**Comment by jacksolutions** [comment]
are you using easyerp in production in your company? is it good?

**Comment by khubo** [comment]
@jacksolutions i am not using it anywhere. 💃 . its a discontinued project with some obvious bugs. I would advice against it unless you plan to work on it urself.

**Comment by jacksolutions** [comment]
started working now :) it seems like when i cloned it , it gets me master version i think,

so i manually downloaded the zip from mongoose branch and now i am in,

thank you for your help, now i am checking how useful it is, will let you know.

yes i have some good plans to make a mobile app based on it and sell in my area :)

so instead of re-inventing the wheel, why not we should use what we have? haha

**Comment by jacksolutions** [comment]
i just checked few pages, working really nice so far
