### ISSUE TITLE
crop button not show in imagecrop popup

### ISSUE THREAD

**Issue by pranaysonisoft** [EasyERP/EasyERP_open_source#2]
Setting -> Users -> Edit Image - Image crop popup

crop button is hidden after mouse hover  on white area near cancel button  text is show slightly.
![screenshot from 2017-01-05 02-17-55](https://cloud.githubusercontent.com/assets/9861931/21658826/1fe9ca00-d2ee-11e6-85e6-a5e745fd9938.png)
![screenshot from 2017-01-05 02-18-07](https://cloud.githubusercontent.com/assets/9861931/21658839/265f5bb6-d2ee-11e6-9d8e-c54665060028.png)

**Comment by PikinerLiliya** [comment]
This was fixed, please check it and we are waiting for your response
